### ISSUE TITLE
Populate This Repo With Input Manifests

### ISSUE THREAD

**Issue by CodeGat** [ACCESS-NRI/model-config-inputs#2]
## Background

We don't currently version inputs. They are too large to put in a `git` repository. @aidanheerdegen and myself were talking about having systems to backup these inputs by adding date-based subdirectories to tape storage (see https://github.com/ACCESS-NRI/model-config-inputs/issues/1#issuecomment-2372731534). This seemed pretty close to having a version control system. 

Instead of versioning the inputs themselves, we can version metadata about the inputs. This also gives a better place to house workflows and actions relating to metadata than the original `model-config-tests` repo. See https://github.com/ACCESS-NRI/model-config-inputs/issues/1

## Implementation Information

Create a directory structure similar to the one that we have on `Gadi` at `/g/data/vk83/configurations/inputs` except instead of the input files themselves, have a `manifest.yaml` file at the leaf of the directory tree that contains metadata about the given inputs. For example:

```
access-esm1p5
├── CHANGELOG
├── modern
│   ├── historical
│   │   ├── atmosphere
│   │   │   ├── aerosol
│   │   │   │   └── global.N96
│   │   │   │       └── 2021.06.22
│   │   │   │           └── manifest.yaml
│   │   │   ├── forcing
│   │   │   │   ├── global.N96
│   │   │   │   │   └── 2021.06.22
│   │   │   │   │       └── manifest.yaml
│   │   │   │   └── resolution_independent
│   │   │   │       └── 2021.06.22
│   │   │   │           └── manifest.yaml
│   │   │   └── land
...
access-om2
...
```

An example of manifests are found in https://github.com/ACCESS-NRI/access-om3-configs/tree/dev-025deg_jra55do_ryf/manifests - but we would probably look to do something slightly different. 

## TODOs

 - [x] Create an equivalent directory structure to `/g/data/vk83/configurations/inputs` in this repository, with the leafs being a single `manifest.yaml`. Consider just `git init`ing on `Gadi` and pushing the result to `main`, once the below is done. 
 - [x] Create a very restrictive `.gitignore` that only tracks the above

**Comment by aidanheerdegen** [comment]
> Create an equivalent directory structure to /g/data/vk83/configurations/inputs in this repository, with the leafs being a single manifest.yaml

Or fetch/clone this repo** into /g/data/vk83/configurations/inputs, generate all the manifests in `/g/data/vk83/configurations/inputs`, and then commit them back to this repo? 


** Some care needs to be taken when cloning into an existing directory. See https://stackoverflow.com/a/36084134/4727812

**Comment by aidanheerdegen** [comment]
There is a (rudimentary) command line interface for `yamanifest` that could be used for this.

Load a `payu` environment that contains `yamanifest`
```
module use /g/data/vk83/prerelease/modules/
module load payu
```

Then the `yamf` cli is available:
```
$ yamf add -h
usage: yamf add [-h] [-n NAME] [-f] [-s HASHES] files [files ...]

positional arguments:
  files                 File paths to add to manifest

options:
  -h, --help            show this help message and exit
  -n NAME, --name NAME  Manifest file name
  -f, --force           Force overwrite of existing manifest
  -s HASHES, --hashes HASHES
                        Use only these hashing functions
```

An example usage: I copied one of the inputs to a local dir and ran `yamf add` to add it to a manifest. This would be the equivalent to running it in each of the input directories.
```
$ cp /g/data/vk83/experiments/inputs/access-esm1p5/modern/historical/atmosphere/land/vegetation/global.N96/2024.07.04/cableCMIP6_LC_1850-2015.nc .
$ yamf add -n manifest.yaml cableCMIP6_LC_1850-2015.nc 
$ cat manifest.yaml 
format: yamanifest
version: 1.0
---
cableCMIP6_LC_1850-2015.nc:
  fullpath: /home/XXX/XXXXXX/cableCMIP6_LC_1850-2015.nc
  hashes:
    binhash: 955dca0d4deedfab795dfce0020454e1
    md5: 78ddfbdc9d9551cf6c6c39fe734716a4
```

**Comment by CodeGat** [comment]
> Or fetch/clone this repo** into /g/data/vk83/configurations/inputs, generate all the manifests in /g/data/vk83/configurations/inputs, and then commit them back to this repo?

So it's a manifest per file rather than a manifest per directory?

**Comment by aidanheerdegen** [comment]
> So it's a manifest per file rather than a manifest per directory?

We've decided on a manifest in each leaf directory. So the first step is to generate these with the service user that has write permission in those directories. Plus we want that user to own the manifests.

**Comment by CodeGat** [comment]
Reminder to add all the current inputs to the tape @CodeGat

**Comment by CodeGat** [comment]
The game plan for adding existing manifests on Gadi to the remote repository without deleting everything (tested locally!):

```bash
git init
git branch -m main
git remote add origin git@github.com:access-nri/model-config-inputs.git
git fetch
git pull origin main --allow-unrelated-histories
git checkout -b add-initial-manifests
git add .
git commit -m "Initial add of manifests"
git push
```

**Comment by CodeGat** [comment]
And in terms of the `.gitignore`, it'll be:

```
*  # ignore everything
!*/  # Allow traversal of directories that are 'ignored' by the above
!manifest.yaml  # Don't ignore manifest files
!.gitignore  # Or the .gitignore itself
```
to ignore everything except for the leaf `manifest.yaml`s. Also verified on Gadi :D
